=== kkolyan/tshooter/shared/src/meta/protocol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://kkolyan.net/schema/protocol"
           xmlns="http://kkolyan.net/schema/protocol">

    <xs:element name="protocol" type="Protocol"/>
    <xs:element name="namespace" type="Namespace"/>
    <xs:element name="type" type="Type"/>
    <xs:element name="value" type="Value"/>
    <xs:element name="sequence" type="Sequence"/>

    <xs:complexType name="Protocol">
        <xs:sequence>
            <xs:element ref="namespace" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="typeIdType" use="required" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="Namespace">
        <xs:choice maxOccurs="unbounded">
            <xs:element ref="type"/>
        </xs:choice>
        <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="Type">
        <xs:choice maxOccurs="unbounded">
            <xs:element ref="value"/>
            <xs:element ref="sequence"/>
        </xs:choice>
        <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>

  <xs:complexType name="Field" abstract="true">
    <xs:attribute name="name" use="required" type="xs:string"/>
    <xs:attribute name="type" use="required" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="Value">
    <xs:complexContent>
      <xs:extension base="Field">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Sequence">
    <xs:complexContent>
      <xs:extension base="Field">
        <xs:attribute name="lengthType" use="required" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== kkolyan/tshooter/shared/src/meta/tshooter.protocol.xml
<protocol xmlns="http://kkolyan.net/schema/protocol"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://kkolyan.net/schema/protocol protocol.xsd" typeIdType="byte">
    <namespace name="net.kkolyan.tshooter.protocol.messages">
        <type name="JoinRoom">
            <value name="roomIndex" type="int"/>
        </type>
        <type name="RoomState">
            <value name="name" type="String"/>
            <value name="index" type="int"/>
            <sequence name="players" type="Player" lengthType="short"/>
            <sequence name="messages" type="String" lengthType="byte"/>
            <sequence name="ports" type="int" lengthType="byte"/>
        </type>
        <type name="Player">
            <value name="index" type="int"/>
            <value name="name" type="String"/>
            <value name="hp" type="float"/>
            <value name="position" type="Vector3f"/>
            <sequence name="weapons" type="Weapon" lengthType="byte"/>
        </type>
        <type name="Weapon">
            <value name="damage" type="float"/>
            <value name="name" type="String"/>
        </type>
        <type name="Vector3f">
            <value name="x" type="float"/>
            <value name="y" type="float"/>
            <value name="z" type="float"/>
        </type>
    </namespace>
</protocol>
